let animal = [
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Armadillo",
    "Donkey",
    "Baboon",
    "Badger",
    "Barracuda",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Bison",
    "Boar",
    "Buffalo",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caribou",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Cattle",
    "Chamois",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chough",
    "Clam",
    "Cobra",
    "Cockroach",
    "Cod",
    "Cormorant",
    "Coyote",
    "Crab",
    "Crane",
    "Crocodile",
    "Crow",
    "Curlew",
    "Deer",
    "Dinosaur",
    "Dog",
    "Dogfish",
    "Dolphin",
    "Dotterel",
    "Dove",
    "Dragonfly",
    "Duck",
    "Dugong",
    "Dunlin",
    "Eagle",
    "Echidna",
    "Eel",
    "Eland",
    "Elephant",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Finch",
    "Fish",
    "Flamingo",
    "Fly",
    "Fox",
    "Frog",
    "Gaur",
    "Gazelle",
    "Gerbil",
    "Giraffe",
    "Gnat",
    "Gnu",
    "Goat",
    "Goldfinch",
    "Goldfish",
    "Goose",
    "Gorilla",
    "Goshawk",
    "Grasshopper",
    "Grouse",
    "Guanaco",
    "Gull",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Human",
    "Hummingbird",
    "Hyena",
    "Ibex",
    "Ibis",
    "Jackal",
    "Jaguar",
    "Jay",
    "Jellyfish",
    "Kangaroo",
    "Kingfisher",
    "Koala",
    "Kookabura",
    "Kouprey",
    "Kudu",
    "Lapwing",
    "Lark",
    "Lemur",
    "Leopard",
    "Lion",
    "Llama",
    "Lobster",
    "Locust",
    "Loris",
    "Louse",
    "Lyrebird",
    "Magpie",
    "Mallard",
    "Manatee",
    "Mandrill",
    "Mantis",
    "Marten",
    "Meerkat",
    "Mink",
    "Mole",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Mouse",
    "Mule",
    "Narwhal",
    "Newt",
    "Nightingale",
    "Octopus",
    "Okapi",
    "Opossum",
    "Oryx",
    "Ostrich",
    "Otter",
    "Owl",
    "Oyster",
    "Panther",
    "Parrot",
    "Partridge",
    "Peafowl",
    "Pelican",
    "Penguin",
    "Pheasant",
    "Pig",
    "Pigeon",
    "Pony",
    "Porcupine",
    "Porpoise",
    "Quail",
    "Quelea",
    "Quetzal",
    "Rabbit",
    "Raccoon",
    "Rail",
    "Ram",
    "Rat",
    "Raven",
    "Red deer",
    "Red panda",
    "Reindeer",
    "Rhinoceros",
    "Rook",
    "Salamander",
    "Salmon",
    "Sand Dollar",
    "Sandpiper",
    "Sardine",
    "Scorpion",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Shrew",
    "Skunk",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Spoonbill",
    "Squid",
    "Squirrel",
    "Starling",
    "Stingray",
    "Stinkbug",
    "Stork",
    "Swallow",
    "Swan",
    "Tapir",
    "Tarsier",
    "Termite",
    "Tiger",
    "Toad",
    "Trout",
    "Turkey",
    "Turtle",
    "Viper",
    "Vulture",
    "Wallaby",
    "Walrus",
    "Wasp",
    "Weasel",
    "Whale",
    "Wildcat",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodcock",
    "Woodpecker",
    "Worm",
    "Wren",
    "Yak",
    "Zebra"
]

const fish = [
    "Angelfish", "Barracuda", "Bass", "Bluegill", "Carp", "Catfish", "Chub", "Cod", "Crappie", "Dolphin Fish",
    "Eel", "Flounder", "Goby", "Grouper", "Haddock", "Halibut", "Herring", "Jackfish", "Lamprey", "Lingcod",
    "Mackerel", "Mahi-mahi", "Mullet", "Murray Cod", "Perch", "Pike", "Pollock", "Rainbow Trout", "Salmon", "Sardine",
    "Sauger", "Shark", "Sheepshead", "Sole", "Sturgeon", "Swordfish", "Tilapia", "Tilefish", "Tuna", "Walleye",
    "Whitefish", "Yellowtail", "Zander", "Bream", "Brill", "Chum Salmon", "Cobia", "Croaker", "Dorado", "Hogfish",
    "Ling", "Mandarin Fish", "Menhaden", "Milkfish", "Monkfish", "Mudfish", "Muskie", "Orange Roughy", "Parrotfish",
    "Pompano", "Rockfish", "Sailfish", "Sea Bass", "Sculpin", "Skipjack Tuna", "Snapper", "Striped Bass", "Sucker",
    "Surfperch", "Threadfin", "Triggerfish", "Trevally", "Wahoo", "Yellowfin Tuna", "Zebra Fish", "Albacore Tuna",
    "Alewife", "Arctic Char", "Bigeye Tuna", "Bluefish", "Bonefish", "Bowfin", "Bullhead", "Butterfish", "Candlefish",
    "Capelin", "Chimaera", "Chinook Salmon", "Clingfish", "Climbing Perch", "Cobia", "Coffinfish", "Crocodile Icefish",
    "Dab", "Deep-Sea Anglerfish", "Dolphinfish", "Duckbill", "Eelpout", "Escolar", "Flying Gurnard", "Four-Eyed Fish",
    "Gar", "Giant Grouper", "Gizzard Shad", "Golden Shiner", "Goldfish", "Goldeye", "Grayling", "Greenling", "Grunt",
    "Gulper Eel", "Haddock", "Hake", "Halfbeak", "Hapuku", "Herring", "Hogfish", "Kahawai", "Kingfish", "Ladyfish",
    "Lake Trout", "Lampfish", "Lemon Shark", "Lemon Sole", "Longnose Gar", "Luminous Hake", "Mackerel", "Madtom",
    "Mahi-Mahi", "Mangrove Red Snapper", "Midshipman Fish", "Minnow", "Moray Eel", "Mudminnow", "Mudskipper",
    "Muskellunge", "Muskfish", "Needlefish", "Nile Perch", "Ocean Sunfish", "Opah", "Paddlefish", "Pearl Danio",
    "Pearl Perch", "Pike", "Pilchard", "Pinfish", "Piranha", "Plaice", "Pomfret", "Porbeagle Shark", "Prickleback",
    "Pufferfish", "Queenfish", "Rainbow Trout", "Ratfish", "Ribbonfish", "Rock Beauty", "Rock Cod", "Rockfish",
    "Rosefish", "Roughy", "Roundhead", "Rudd", "Sablefish", "Sailfish", "Salamanderfish", "Sardine", "Saury",
    "Sawfish", "Scad", "Scorpionfish", "Sculpin", "Sea Bass", "Sea Bream", "Sea Devil", "Sea Dragon", "Sea Trout",
    "Shad", "Sharksucker", "Sheatfish", "Silverside", "Skate", "Skipjack Tuna", "Sleeper", "Smelt", "Snakehead",
    "Snook", "Sockeye Salmon", "Soldierfish", "Spanish Mackerel", "Speckled Trout", "Spearfish", "Spearfish", "Stargazer",
    "Stickleback", "Sturgeon", "Sunfish", "Surgeonfish", "Swordfish", "Tang", "Tarpon", "Tench", "Tilapia", "Tilefish",
    "Toadfish", "Tomcod", "Triggerfish", "Tripodfish", "Tuna", "Turbot", "Vampire Squid", "Velvet Belly Lanternshark",
    "Wahoo", "Walleye", "Whale Shark", "Wobbegong", "Worm Eel", "Yellow Perch", "Yellowtail Amberjack", "Zebra Lionfish",
    "Zebra Shark"
];


let plant = [  	"alder",

"black alder",
"common alder",
"false alder",
"gray alder",
"speckled alder",
"striped alder",
"white alder",
"almond",
"ambrosia",
"tall ambrosia",
"amy root",
"angel trumpet",
"apple",
"apricot",
"arfaj",
"arizona sycamore",
"arrowwood",
"indian arrowwood",
"ash",
"black ash",
"blue ash",
"cane ash",
"green ash",
"maple ash",
"red ash",
"river ash",
"swamp ash",
"white ash",
"water ash",
"azolla",
"carolina azolla",
"bamboo",
"banana",
"baobab",
"bay",
"bay laurel",
"california bay",
"bean",
"bearberry",
"bear corn",
"beech",
"bindweed",
"blue bindweed",
"bird's nest",
"bird's nest plant",
"birch",
"black birch",
"bolean birch",
"canoe birch",
"cherry birch",
"european weeping birch",
"european white birch",
"gray birch",
"mahogany birch",
"paper birch",
"red birch",
"river birch",
"silver birch",
"spice birch",
"sweet birch",
"water birch",
"weeping birch",
"white birch",
"yellow birch",
"bittercress",
"hairy bittercress",
"bittersweet",
"trailing bittersweet",
"bitterweed",
"blackberry",
"hispid swamp blackberry",
"pennsylvania blackberry",
"running swamp blackberry",
"black cap",
"black-eyed susan",
"blackhaw",
"blackiehead",
"black-weed",
"blueberry",
"blue-of-the-heavens",
"bow-wood",
"box",
"false box",
"boxelder",
"boxwood",
"false boxwood",
"brier",
"sand brier",
"brittlebush",
"broadleaf",
"brown betty",
"brown-eyed susan",
"buckeye",
"buckeye",
"buffalo weed",
"butterfly flower",
"butterfly weed",
"columbine",
"cabbage",
"clumpfoot cabbage",
"meadow cabbage",
"skunk cabbage",
"swamp cabbage",
"california bay",
"california buckeye",
"california sycamore",
"california walnut",
"canada root",
"cancer jalap",
"carrot",
"wild carrot",
"carrot weed",
"cart track plant",
"catalina ironwood",
"cherry",
"black cherry",
"cabinet cherry",
"rum cherry",
"whiskey cherry",
"wild cherry",
"wild black cherry",
"chestnut",
"chigger flower",
"chrysanthemum",
"cinnamon",
"clove",
"clover",
"coakum",
"coconut",
"coffee plant",
"colic weed",
"collard",
"columbine",
"colwort",
"hare's colwort",
"coneflower",
"brilliant coneflower",
"cutleaf coneflower",
"eastern coneflower",
"green-headed coneflower",
"orange coneflower",
"tall coneflower",
"thin-leaved coneflower",
"three-leaved coneflower",
"cornel",
"blueberry cornel",
"silky cornel",
"white cornel",
"cornelian tree",
"corydalis",
"fern-leaf corydalis",
"golden corydalis",
"pale corydalis",
"pink corydalis",
"yellow corydalis",
"cotton plant",
"creeping yellowcress",
"cress",
"american cress",
"bank cress",
"belle isle cress",
"bermuda cress",
"bulbous cress",
"lamb's cress",
"land cress",
"scurvy cress",
"spring cress",
"upland cress",
"crowfoot",
"crow's nest",
"crow's toes",
"cucumber",
"flowering dogwood",
"daisy",
"brown daisy",
"common daisy",
"gloriosa daisy",
"poorland daisy",
"yellow daisy",
"yellow ox-eye daisy",
"deadnettle",
"henbit deadnettle",
"red deadnettle",
"spotted deadnettle",
"devil's bite",
"devil's darning needle",
"devil's nose",
"devil's plague",
"dewberry",
"bristly dewberry",
"swamp dewberry",
"dindle",
"dogwood",
"american dogwood",
"florida dogwood",
"flowering dogwood",
"japanese flowering dogwood",
"kousa dogwood",
"drumstick",
"pacific dogwood",
"silky dogwood",
"swamp dogwood",
"duck retten",
"duscle",
"durian",
"durian kura kura",
"durian munjit",
"durian pulu",
"red durian",
"dye-leaves",
"easter orchid",
"easter orchid",
"earth gall",
"elderberry",
"elegant lupine",
"elephant apple",
"english bull's eye",
"eucalyptus",
"evergreen huckleberry",
"extinguisher moss",
"eytelia",
"fellenwort",
"fair-maid-of-france",
"fairymoss azolla caroliniana",
"fellenwort",
"felonwood",
"felonwort",
"fennel",
"ferns",
"boston fern or sword fern",
"christmas fern",
"coast polypody",
"kimberly queen fern",
"korean rock fern",
"mosquito fern",
"sword ferns",
"water fern",
"western sword fern",
"feverbush",
"feverfew",
"fig",
"common fig",
"flax",
"european flax",
"new zealand flax",
"fluxroot",
"fumewort",
"yellow fumewort",
"golden chain",
"gallberry",
"garget",
"garlic",
"golden garlic",
"wild garlic",
"garlic mustard",
"garlic root",
"gilliflower",
"dame's gilliflower",
"night scented gilliflower",
"queen's gilliflower",
"rogue's gilliflower",
"winter gilliflower",
"golden buttons",
"golden chain",
"goldenglow",
"golden jerusalem",
"gordaldo",
"goose tongue",
"grapefruit",
"grapevine",
"groundberry",
"bristly groundberry",
"gutweed",
"hellebore",
"haldi",
"harlequin",
"rock harlequin",
"yellow harlequin",
"hay fever weed",
"healing blade",
"hedge plant",
"hellebore",
"american white hellebore",
"big hellebore",
"black hellebore",
"european white hellebore",
"false hellebore",
"swamp hellebore",
"white hellebore",
"hemp",
"hemp dogbane",
"hen plant",
"herb barbara",
"hogweed",
"holly",
"deciduous holly",
"european holly",
"inkberry holly",
"meadow holly",
"swamp holly",
"winterberry holly",
"horse cane",
"hound's berry",
"huckleberry",
"evergreen huckleberry",
"trailing red huckleberry",
"houseleek",
"ivy",
"indian hemp",
"indian hemp",
"white indian hemp",
"indian paintbrush",
"indian posy",
"inkberry",
"ironwood",
"isle of man cabbage",
"itchweed",
"ivy",
"jasmine",
"jack-by-the-hedge",
"jack-in-the-bush",
"jasmine",
"jewel orchid",
"jointed rush",
"jugflower",
"juneberry",
"juniper",
"kudzu",
"keek",
"king fern",
"kinnikinnik",
"kittentail",
"knotweed",
"kousa",
"kudzu",
"kumarahou",
"lavender",
"laceflower",
"lace fern",
"lamb's foot",
"latanier palm",
"laurel magnolia",
"lavender",
"leek",
"lemon",
"leopard lily",
"lily of the nile",
"lettuce",
"lily leek",
"lilac",
"summer lilac",
"little sunflower",
"lone fleabane",
"love vine",
"petty morel",
"maize",
"mango",
"maple",
"ash-leaved maple",
"black maple",
"creek maple",
"cutleaf maple",
"maple ash",
"moose maple",
"red river maple",
"river maple",
"silver maple",
"silverleaf maple",
"soft maple",
"striped maple",
"sugar maple",
"swamp maple",
"water maple",
"white maple",
"mesquite",
"honey mesquite",
"screwbean mesquite",
"milfoil",
"milkweed",
"blunt-leaved milkweed",
"common milkweed",
"horsetail milkweed",
"orange milkweed",
"swamp milkweed",
"rose milkweed",
"whorled milkweed",
"yellow milkweed",
"milky tassel",
"moosewood",
"morel",
"petty morel",
"mosquito plant",
"mother-of-the-evening",
"mountain mahogany",
"mulberry",
"red mulberry",
"white mulberry",
"native fuchsia",
"native fuchsia",
"necklace fern",
"neem",
"nettle",
"bull nettle",
"carolina horse nettle",
"horse nettle",
"night-blooming cactus",
"nightshade",
"american nightshade",
"bitter nightshade",
"black nightshade",
"climbing nightshade",
"deadly nightshade",
"garden nightshade",
"trailing nightshade",
"trailing violet nightshade",
"woody nightshade",
"nodding wakerobin",
"northern moonwort",
"nosebleed",
"sweet orange",
"oak tree -quercus",
"algerian oak quercus canariensis",
"blue oak",
"bur oak",
"california black oak quercus kelloggii",
"canyon live oak quercus chrysolepis",
"champion oak",
"coast live oak",
"cork oak",
"dyer's oak",
"eastern black oak",
"english oak",
"island oak",
"mirbeck's oak",
"mossycup white oak",
"northern red oak",
"pedunculate oak",
"pin oak",
"red oak",
"scarlet oak",
"scrub oak",
"sessile oak",
"spanish oak",
"spotted oak",
"swamp oak",
"swamp spanish oak",
"swamp white oak",
"valley oak",
"white oak",
"yellowbark oak",
"olive",
"onion",
"common onion",
"giant onion",
"nodding onion",
"tree onion",
"wild onion",
"orange",
"osage orange",
"sweet orange",
"wild orange",
"orange-root",
"osage",
"osier",
"red osier",
"golden poppy",
"parsley",
"parsnip",
"pea",
"peach",
"peanut",
"pear",
"pellitory",
"bastard pellitory",
"european pellitory",
"wild pellitory",
"penny hedge",
"pepper root",
"pigeon berry",
"pine",
"pineapple",
"pistachio",
"plane",
"plantain",
"broadleaf plantain",
"common plantain",
"dooryard plantain",
"greater plantain",
"roundleaf plantain",
"wayside plantain",
"pleurisy root",
"pocan bush",
"poison ivy",
"poisonberry",
"poisonflower",
"poke",
"indian poke",
"pokeroot",
"pokeweed",
"polkweed",
"polecat weed",
"poor annie",
"poor man's mustard",
"poplar",
"poppy",
"possumhaw",
"potato",
"queen anne's lace",
"quercitron",
"multiflora rose",
"radical weed",
"ragweed",
"common ragweed",
"giant ragweed",
"great ragweed",
"ragwort",
"common ragwort",
"hoary ragwort",
"marsh ragwort",
"oxford ragwort",
"silver ragwort",
"rantipole",
"rapeseed",
"raspberry",
"black raspberry",
"purple raspberry",
"redbrush",
"redbud",
"eastern redbud",
"western redbud",
"judas-tree",
"red ink plant",
"redweed",
"rheumatism root",
"rhubarb",
"ribwort",
"rice",
"asian rice",
"african rice",
"roadweed",
"rocket",
"dame's rocket",
"sweet rocket",
"winter rocket",
"yellow rocket",
"rocketcress",
"rose",
"baby rose",
"dwarf wild rose",
"low rose",
"multiflora rose",
"prairie rose",
"rambler rose",
"wild rose",
"rosemary",
"rye",
"snowdrop",
"saffron crocus",
"sanguinary",
"saskatoon",
"sauce-alone",
"scarlet berry",
"scoke",
"scotch cap",
"scrambled eggs",
"scurvy grass",
"serviceberry",
"common serviceberry",
"downy serviceberry",
"shadblow serviceberry",
"shadblow",
"shadbush",
"silkweed",
"swamp silkweed",
"virginia silkweed",
"skunkweed",
"snakeberry",
"snowdrop",
"sorrel",
"redwood sorrel",
"speedwell",
"corn speedwell",
"wall speedwell",
"spoolwood",
"squaw bush",
"stammerwort",
"star-of-persia",
"stickweed",
"strawberry",
"strawberry tree",
"strawberry tree 'marina'",
"sugarcane",
"swallow-wort",
"orange swallow-wort",
"silky swallow-wort",
"sneezeweed",
"sneezewort",
"sunflower",
"sugarplum",
"soldier's woundwort",
"stag bush",
"swallow-wort",
"orange swallow-wort",
"silky swallow-wort",
"sweet potato",
"sweet potato vine",
"swinies",
"sycamore",
"sycamore",
"sycamore",
"sycamore",
"sundari",
"gewa",
"tobacco plant",
"tansy",
"common tansy",
"white tansy",
"wild tansy",
"tea",
"appalachian tea",
"thimbleberry",
"thimbleweed",
"thousand-leaf",
"thousand-seal",
"tassel weed",
"thistle",
"annual sow thistle",
"california thistle",
"canada thistle",
"corn thistle",
"corn sow thistle",
"creeping thistle",
"cursed thistle",
"field sow thistle",
"green thistle",
"hard thistle",
"hare's thistle",
"milk thistle",
"nodding thistle",
"perennial thistle",
"prickly thistle",
"sharp-fringed sow thistle",
"small-flowered thistle",
"spiny sow thistle",
"spiny-leaved sow thistle",
"swine thistle",
"tree sow thistle",
"way thistle",
"thyme",
"tickleweed",
"tobacco plant",
"tomato",
"toothwort",
"cutleaf toothwort",
"purple-flowered toothwort",
"touch-me-not",
"traveller's joy",
"tread-softly",
"tree tobacco",
"trillium",
"western trillium",
"western wake robin",
"white trillium",
"tuber-root",
"tulip",
"tulsi",
"umbrella palm",
"umbrella papyrus",
"voodoo lily",
"vanilla orchid",
"varnish tree",
"velvet bean",
"viburnum",
"blackhaw viburnum",
"leatherleaf viburnum",
"violet",
"viola species",
"african violet",
"damask violet",
"dame's violet",
"dog's-tooth-violet or dogtooth violet",
"violet bloom",
"viper's grass",
"virgin's bower",
"virginia virgin's bower",
"voodoo lily",
"woolly morning glory",
"walnut",
"walnut",
"waybread",
"western redbud",
"wheat",
"white man's foot",
"white-root",
"wild cotton",
"wild hops",
"willow",
"coyote willow",
"goodding willow",
"red willow",
"rose willow",
"windroot",
"wineberry",
"winterberry",
"american winterberry",
"evergreen winterberry",
"virginia winterberry",
"wintercress",
"early wintercress",
"woodbine",
"woolly morning glory",
"wormwood",
"roman wormwood",
"wound rocket",
"yellow coneflower",
"yarrow",
"common yarrow",
"fernleaf yarrow",
"sneezewort yarrow",
"woolly yarrow",
"yellow fieldcress",
"yellowwood",
"yellow coneflower",
"yam",
"yunnan camellia",
"zebrawood",
"zebrawood",
"zedoary"];

const bird =[
    "Common Loon", "Red-throated Loon", "Pacific Loon", "Arctic Loon", "Yellow-billed Loon",
    "Pied-billed Grebe", "Horned Grebe", "Red-necked Grebe", "Eared Grebe", "Western Grebe",
    "Clark's Grebe", "Northern Fulmar", "Giant Petrel", "Cape Petrel", "Snow Petrel",
    "Fairy Prion", "Antarctic Prion", "Slender-billed Prion", "Bulwer's Petrel", "White-chinned Petrel",
    "Black-winged Petrel", "Great-winged Petrel", "Light-mantled Albatross", "Wandering Albatross", "Northern Royal Albatross",
    "Black-browed Albatross", "Grey-headed Albatross", "Atlantic Yellow-nosed Albatross", "Indian Yellow-nosed Albatross", "Shy Albatross",
    "Salvin's Albatross", "Chatham Albatross", "White-capped Albatross", "Buller's Albatross", "Northern Giant Petrel",
    "Southern Giant Petrel", "Streaked Shearwater", "Flesh-footed Shearwater", "Wedge-tailed Shearwater", "Buller's Shearwater",
    "Short-tailed Shearwater", "Sooty Shearwater", "Great Shearwater", "Pink-footed Shearwater", "Manx Shearwater",
    "Fairy Shearwater", "Wilson's Storm Petrel", "White-faced Storm Petrel", "Black-bellied Storm Petrel", "Least Storm Petrel",
    "European Storm Petrel", "Swinhoe's Storm Petrel", "Leach's Storm Petrel", "Fork-tailed Storm Petrel", "Ringed Storm Petrel",
    "Kerguelen Petrel", "Atlantic Petrel", "Great-winged Petrel", "Cory's Shearwater", "Scopoli's Shearwater",
    "Balearic Shearwater", "Tahiti Petrel", "Kermadec Petrel", "Herald Petrel", "Mascarene Petrel", "Bermuda Petrel",
    "Black-capped Petrel", "Galapagos Petrel", "Juan Fernandez Petrel", "Capped Petrel", "Soft-plumaged Petrel",
    "Fea's Petrel", "Zino's Petrel", "Barau's Petrel", "Desertas Petrel", "Stejneger's Petrel", "Trindade Petrel",
    "Cape Verde Petrel", "Band-rumped Storm Petrel", "Bulwer's Petrel", "Jouanin's Petrel", "Parkinson's Petrel",
    "White-headed Petrel", "Cook's Petrel", "Gould's Petrel", "Grey Petrel", "White-necked Petrel", "Blue Petrel",
    "Broad-billed Prion", "Salvin's Prion", "Fairy Prion", "Slender-billed Prion", "Antarctic Prion", "Dove Prion",
    "Tasman Prion", "Thin-billed Prion", "Macaronesian Shearwater", "Madeiran Storm Petrel", "European Storm Petrel",
    "Wilson's Storm Petrel", "Black-bellied Storm Petrel", "White-faced Storm Petrel", "Leach's Storm Petrel", "Fork-tailed Storm Petrel",
    "Red-billed Tropicbird", "White-tailed Tropicbird", "Red-tailed Tropicbird", "Red-footed Booby", "Brown Booby",
    "Masked Booby", "Blue-footed Booby", "Peruvian Booby", "Nazca Booby", "Northern Gannet", "Australasian Gannet",
    "Cape Gannet", "Boerboel", "Peregrine Falcon", "Prairie Falcon", "Barbary Falcon", "Australian Hobby",
    "New Zealand Falcon", "Aplomado Falcon", "American Kestrel", "Merlin", "Eurasian Hobby", "Eleonora's Falcon",
    "Sooty Falcon", "Amur Falcon", "Grey Falcon", "Red-footed Falcon", "Brown Falcon", "Black Falcon",
    "Bare-eyed Cockatoo", "Blue-eyed Cockatoo", "Glossy Black Cockatoo", "Red-tailed Black Cockatoo", "Yellow-tailed Black Cockatoo",
    "Short-billed Black Cockatoo", "Long-billed Black Cockatoo", "Carnaby's Black Cockatoo", "Baudin's Black Cockatoo", "Forest Red-tailed Black Cockatoo",
    "Wedge-tailed Eagle", "White-bellied Sea Eagle", "Steller's Sea Eagle", "Bald Eagle", "Golden Eagle"]

